# Site wide configuration

title: Justin Lee
description: Check out Justin's most recent shenanigans
logo: # 120x120 px default image used for Twitter summary card
teaser: train_banner.jpg # 400x250 px default teaser image used in image archive grid
locale:
#url: http://localhost:4000
#url: http://leejustin.github.io
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Justin Lee
  email: isjustintime@gmail.com
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
